### ISSUE TITLE
detectiveking - Account for edge case where gOHM is sent to ClearingHouse

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-08-cooler-judging#162]
detectiveking

medium

# Account for edge case where gOHM is sent to ClearingHouse
## Summary

There are currently two ways through which one can deal with defaulted loans: either through `claimDefaulted` in `ClearingHouse.sol` or through directly calling `claimDefaulted` in `Cooler.sol` (though in the latter case you don't receive a keeper reward). In the event that a user calls `claimDefaulted` in `Cooler.sol` for a loan that was given by the ClearingHouse, the ClearingHouse will be transferred the gOHM but it will not be burned.

## Vulnerability Detail

First, a regular user takes out a loan through the ClearingHouse but does not pay it back and the expiration period passes. Then, another user calls `claimDefaulted` in `Cooler.sol` (so directly through the Cooler). The gOHM collateral will be sent back to the ClearingHouse (since the clearing house was the lender), but it will  not be burned like it as at the end of `claimDefaulted` in `ClearingHouse.sol`. The fact that the collateral gOHM is not burned will be quite unfortunate for larger loans with higher amounts of collateral. 

## Impact

gOHM collateral for defaulted loans given by ClearingHouse will not necessarily be burned. 

## Code Snippet

https://github.com/sherlock-audit/2023-08-cooler/blob/main/Cooler/src/Cooler.sol#L318-L333

## Tool used

Manual Review

## Recommendation

I would recommend ensuring that `msg.sender` is the ClearingHouse at the beginning of `claimDefaulted` in `Cooler.sol`. However, if for some reason you're unwilling to do this, I would recommend also transferring out all the `gOHM` in the contract in `emergencyShutdown`. 

Duplicate of #46

**Comment by 0xmonrel** [comment]
Escalate 

Duplicate of #46

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> Duplicate of #46 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Oot2k** [comment]
Agree with escalation

**Comment by jkoppel** [comment]
Also agreed.

**Comment by hrishibhat** [comment]
Result:
Medium 
Duplicate of #46

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xmonrel](https://github.com/sherlock-audit/2023-08-cooler-judging/issues/162/#issuecomment-1715994477): accepted
