### ISSUE TITLE
Chinmay - Lender can force defaulting of a loan without the borrower's permission

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-08-cooler-judging#186]
Chinmay

high

# Lender can force defaulting of a loan without the borrower's permission
## Summary
There is an option for the lender to set repayDirect to true if he wants to get paid the loan amount directly. But he can set the lender address to a blacklisted address and the borrower will never be able to repay the loan, leading to forced default. 

## Vulnerability Detail
The same issue was found in the first sherlock audit [here](https://github.com/sherlock-audit/2023-08-cooler-chinmay-farkya/issues/new?assignees=&labels=&projects=&template=audit-item.md&title=) and there has been an attempt to fix it, but it is still not resolved. 

If a lender wants the borrower's collateral forcefully, he can set the ```repayDirect``` to true via ```setRepay``` function and then call ```transferOwnership``` to change lender address to one that is blacklisted by the debt ERC20 token (ex. USDC/USDT) and is controlled by him. Any calls to ```repayLoan``` will thus revert and then he will wait for the loan to default. After loan expiry, he can call ```claimDefaulted``` to claim the collateral.

## Impact
The borrower will lose all pending collateral and can even lose whole of his collateral unnecessarily. 

## Code Snippet
https://github.com/sherlock-audit/2023-08-cooler/blob/main/Cooler/src/Cooler.sol#L359

## Tool used
Manual Review

## Recommendation
Either include the repayDirect immutable value in the loan request information so that both parties can agree on the process, or require the borrower's approval while changing the lender address so that he can verify.

**Comment by chinmay-farkya** [comment]
Escalate

The comment at [Cooler.sol#230](https://github.com/sherlock-audit/2023-08-cooler-chinmay-farkya/blob/1dc9a6189af5738c48712edebf427208480bcfb7/Cooler/src/Cooler.sol#L230) says that the repayDirect feature is present to protect lender from blacklisting problems. The presence of this comment means that blacklisting tokens like USDC/USDT are allowed in a generic Cooler. 

However, the repayDirect feature doesn't protect the borrower from blacklisting problems. Consider this scenario : a loan request is put up, only the lender has a say in if repayDirect feature will be used. Now later, the lender can change this stored lender address via transferOwnership function. Lender can change this address abruptly anytime without the borrower knowing and so lender may put a blacklisted address.

Thus, now repayLoan will not work and the loan will be forcefully defaulted. This is unfair to the borrower.

Moreover, repayDirect may be set to false during initial loan request clearing but Lender can easily change it to true using setDirectRepay function without the borrower knowing. 

repayDirect feature exists to protect lender from blacklisting problems but the borrower is not protected from these problems. 
All loan parameters and information like addresses or repayDirect value should be only set when both parties agree.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The comment at [Cooler.sol#230](https://github.com/sherlock-audit/2023-08-cooler-chinmay-farkya/blob/1dc9a6189af5738c48712edebf427208480bcfb7/Cooler/src/Cooler.sol#L230) says that the repayDirect feature is present to protect lender from blacklisting problems. The presence of this comment means that blacklisting tokens like USDC/USDT are allowed in a generic Cooler. 
> 
> However, the repayDirect feature doesn't protect the borrower from blacklisting problems. Consider this scenario : a loan request is put up, only the lender has a say in if repayDirect feature will be used. Now later, the lender can change this stored lender address via transferOwnership function. Lender can change this address abruptly anytime without the borrower knowing and so lender may put a blacklisted address.
> 
> Thus, now repayLoan will not work and the loan will be forcefully defaulted. This is unfair to the borrower.
> 
> Moreover, repayDirect may be set to false during initial loan request clearing but Lender can easily change it to true using setDirectRepay function without the borrower knowing. 
> 
> repayDirect feature exists to protect lender from blacklisting problems but the borrower is not protected from these problems. 
> All loan parameters and information like addresses or repayDirect value should be only set when both parties agree. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Oot2k** [comment]
Sherlock contest page states that only 3 tokens without blacklist are supported. I think for this reason this issue is a valid low!

**Comment by chinmay-farkya** [comment]
> Sherlock contest page states that only 3 tokens without blacklist are supported. I think for this reason this issue is a valid low!

I think that may be true for the ClearingHouse integrating with OHM, but the generic cooler can operate with popular tokens like USDC, and that is why the repayDirect functionality has been included in the code. The code and the mentioned comment must take priority.

**Comment by midori-fuse** [comment]
Would like to provide my own opinion.

This is a weird case that I am not sure how the rules will work. This finding is meant to highlight a previous contest's finding that was (supposedly) insufficiently addressed. Given that this is technically an update contest, there is reasoning for this issue to be both valid and invalid.

The severity is definitely high [as per the original contest's corresponding issue](https://github.com/sherlock-audit/2023-01-cooler-judging/issues/23), and at least #143 , #146 , #134 , #10 , are dupes of this. The only question is whether this issue is valid or not, i.e. what rule are we going by here.

I think the wise decision is to reward this one, given that they have pointed out an overlooked issue, and furthermore there is a punishment mechanism for invalid issues that may disincentivize out-of-the-box submissions like these in the future.

**Comment by detectiveking123** [comment]
Feel like it should be in scope, especially since it was in scope in the previous contest and the change made was incorrect.

**Comment by jkoppel** [comment]
One thing that's changed is that Sherlock now has a questionnaire about tokens the contract will work with and weird tokens . No blacklisted token is mentioned.

**Comment by chinmay-farkya** [comment]
> One thing that's changed is that Sherlock now has a questionnaire about tokens the contract will work with and weird tokens . No blacklisted token is mentioned.

Since the code has the mentioned feature (which is in scope) and since the Cooler contract is a generic borrowing mechanism, I think details filled for tokens are for the ClearingHouse but not for the Cooler, so it seems incorrect that Cooler would only be used for the 3 mentioned tokens. The code decides the scope.

**Comment by hrishibhat** [comment]
Result:
Low
Unique 
Agree that this issue is a valid low given that the readme indicates only 3 tokens to be interacting with these smart contracts

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [chinmay-farkya](https://github.com/sherlock-audit/2023-08-cooler-judging/issues/186/#issuecomment-1715366462): rejected
