### ISSUE TITLE
BugBusters - reorg attack due to usage of clone

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-08-cooler-judging#233]
BugBusters

medium

# reorg attack due to usage of clone
## Summary
An attacker can steal funds via a reorg attack if a contract is funded within a few blocks of being created inside a factory.

## Vulnerability Detail
Re-orgs can happen in all EVM chains. In ethereum, where currently Cooler is deployed, it is not "super common" but it still happens.

https://decrypt.co/101390/ethereum-beacon-chain-blockchain-reorg

https://cointelegraph.com/news/ethereum-beacon-chain-experiences-7-block-reorg-what-s-going-on

The issue would happen when users rely on the address derivation in advance or try to deploy the position clone with the same address on different EVM chains, any funds sent to the new clone could potentially be withdrawn by anyone else. All in all, it could lead to the theft of user funds.

due to low probability i'm marking this as Medium

## Impact
Funds could be loss

## Code Snippet
```solidity
            cooler = address(coolerImplementation).clone(coolerData); //@audit clone deterministic
```

https://github.com/sherlock-audit/2023-08-cooler/blob/main/Cooler/src/CoolerFactory.sol#L71

## Tool used

Manual Review

## Recommendation
use `cloneDeterministic` as `cloneDeterministic` uses the opcode and a salt to deterministically deploy the clone. Using the same implementation and salt multiple times will revert since the clones cannot be deployed twice at the same address.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol

**Comment by ghost** [comment]
Escalate for 10 usdc

this is a valid issue and historically its marked as valid

**Comment by sherlock-admin2** [comment]
> Escalate for 10 usdc
> 
> this is a valid issue and historically its marked as valid

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by hamza442-ali** [comment]
Escalate for 10 usdc

this is a valid issue as it is a known issue with clone.
