### ISSUE TITLE
Kow - Lenders can force borrowers to default using CoolerCallback

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-08-cooler-judging#50]
Kow

high

# Lenders can force borrowers to default using CoolerCallback
## Summary
Lenders can prevent the borrower from repaying their loan by always reverting on the ``onRepay`` callback, forcing a default and taking the borrower's collateral for profit.

## Vulnerability Detail
``Cooler`` allows lenders to lend using a contract that implements the functions in ``CoolerCallback``. The ``onRepay`` callback can be enabled by the lender when they call ``clearRequest`` on a borrower's request. If ``loan.callback = true``, this callback is always called in ``repayLoan``. If the lender implements ``onRepay`` such that it always reverts, the borrower cannot repay their loan and is forced to default.

## Impact
Borrower cannot repay their loan and loses collateral (at a loss).

## Code Snippet
https://github.com/sherlock-audit/2023-08-cooler/blob/6d34cd12a2a15d2c92307d44782d6eae1474ab25/Cooler/src/Cooler.sol#L185
https://github.com/sherlock-audit/2023-08-cooler/blob/6d34cd12a2a15d2c92307d44782d6eae1474ab25/Cooler/src/Cooler.sol#L233-L275

## Tool used

Manual Review

## Recommendation
Wrap the callback in a try catch block leaving the lender to manage their own errors. This could be exclusively applied to lenders that are not the ``Clearinghouse`` if reverting is desired for potential issues in ``Clearinghouse`` callbacks.

Duplicate of #187

**Comment by 0xrusowsky** [comment]
- https://github.com/ohmzeus/Cooler/pull/50
